node_type_risposte_status: '1'
node_type_risposte_pattern: '[node:nid]'
node_type_risposte_php: 0
submit: 'Salva configurazione'
form_build_id: form-dLrLAFs9CGw3Xyh_bnjHeb_HQwaVqrwD-1mM1nZ-BBY
form_token: twKbbVjzcdPkt5WrTXhyBNXm-VbOGvvoCre92QZJlfg
form_id: auto_entitylabel_settings_form
op: 'Salva configurazione'
